# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: subrepos1
    endpoint: agahkarakuzu
    type: github
    name: agahkarakuzu/rrsg2019.om
  - repository: subrepos2
    endpoint: agahkarakuzu
    type: github
    name: agahkarakuzu/rrsg2019.py
 
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: subrepos1
- checkout: subrepos2

- script: dir $(Build.SourcesDirectory)
